packages:
  create:
    main: github.com/TIBCOSoftware/flogo-cli/cmd/flogo
    distance-to-project-pkg: 3
    # omit-vendor-dirs: true
  device:
    main: github.com/TIBCOSoftware/flogo-cli/cmd/flogodevice
    distance-to-project-pkg: 3
    # omit-vendor-dirs: true
  gen:
    main: github.com/TIBCOSoftware/flogo-cli/cmd/flogogen
    distance-to-project-pkg: 3
    # omit-vendor-dirs: true
  fgen:
    main: github.com/retgits/fgen
  # nb. disabled for now as it needs to rename 'fgstate.go' to 'main.go'
  # fgstore:
  #  main: github.com/TIBCOSoftware/flogo-services/flow-state/cmd/fgstate
  #  distance-to-project-pkg: 3
  # nb. disabled for now as it needs to rename 'fgstore.go' to 'main.go'
  # fsvc:
  #  main: github.com/TIBCOSoftware/flogo-services/flow-store/cmd/fgstore
  #  distance-to-project-pkg: 3
  web:
    main: github.com/retgits/flogowebhelper
    # omit-vendor-dirs: true
  dio:
    main: github.com/retgits/fdio
    # omit-vendor-dirs: true
  lazygit:
    main: github.com/jesseduffield/lazygit
    # omit-vendor-dirs: true
  gc:
    main: github.com/retgits/gc
    # omit-vendor-dirs: true
  ghhelper:
    main: github.com/retgits/ghhelper
    # omit-vendor-dirs: true
  bulldozer:
    main: github.com/palantir/bulldozer
    # omit-vendor-dirs: true
  # nb. error: unexpected directory layout
  # dep:
  #  main: github.com/golang/dep/cmd/dep
  #  distance-to-project-pkg: 2
  #  omit-vendor-dirs: true
  # crane:
  #  main: github.com/michaelsauter/crane
  #  omit-vendor-dirs: true
  # mcc:
  #  main: github.com/qmu/mcc
  #  omit-vendor-dirs: true
  distgo:
    main: github.com/palantir/distgo
    # omit-vendor-dirs: true
  # deadcode:
  #  main: github.com/remyoudompheng/go-misc/deadcode
  errcheck:
    main: github.com/kisielk/errcheck
    # omit-vendor-dirs: true
  golint:
    main: github.com/golang/lint/golint
    distance-to-project-pkg: 1
    # omit-vendor-dirs: true
  govet:
    main: github.com/nmiyake/govet
    # omit-vendor-dirs: true
  ineffassign:
    main: github.com/gordonklaus/ineffassign
    # omit-vendor-dirs: true
  unconvert:
    main: github.com/mdempsky/unconvert
    # omit-vendor-dirs: true
  varcheck:
    main: github.com/opennota/check/cmd/varcheck
    # omit-vendor-dirs: true
  apk-file:
    main: github.com/genuinetools/apk-file
    # omit-vendor-dirs: true