# Sniperkit-Bot
# - Status: analyzed

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: payment-go-svc
  name: payment-go-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: payment-go-svc
  template:
    metadata:
      labels:
        run: payment-go-svc
    spec:
      containers:
      - name: payment-go-svc
        image: retgits/paymentservice-go:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: payment-go-svc
  name: payment-go-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: payment-go-svc
  sessionAffinity: None
  type: ClusterIP
